FROM lmcache/lmstack-router:v0.1.10

USER root

ARG APP_UID=10001
ARG APP_GID=10001

COPY docker-entrypoint-lmrouter-secrets.sh /usr/local/bin/docker-entrypoint-lmrouter-secrets.sh

RUN set -eux; \
    if ! getent group vllmuser >/dev/null 2>&1; then \
        groupadd --gid "$APP_GID" vllmuser; \
    fi; \
    if ! id -u vllmuser >/dev/null 2>&1; then \
        useradd --uid "$APP_UID" --gid "$APP_GID" --create-home --shell /bin/sh vllmuser; \
    fi; \
    chmod 755 /usr/local/bin/docker-entrypoint-lmrouter-secrets.sh

WORKDIR /home/vllmuser
USER vllmuser

ENTRYPOINT ["/usr/local/bin/docker-entrypoint-lmrouter-secrets.sh"]